### ISSUE TITLE
Problem Importing Modpack via SKlauncher

### ISSUE THREAD

**Issue by bronzecheese** [PewPewCricket/MSG-Community-Edition#2]
After using the zip import feature, the progress window and the modpack do not appear in the modpack panel. It does not give an error message. Most likely this is due to the fact that SKlauncher does not support packwiz modpacks. Will there be a non-packwiz version of the modpack? Rather, this is not an issue, but a different modpack version request.

**Comment by PewPewCricket** [comment]
The next release will have a Curseforge formatted zip which should work on all launchers, thank you for informing me!

**Comment by PewPewCricket** [comment]
A Curseforge zip is now available under the new release.

**Comment by bronzecheese** [comment]
Thank you very much! I will try it out tomorrow and let you know.
