### ISSUE TITLE
Problems with Prism

### ISSUE THREAD

**Issue by LynxDolphin** [PewPewCricket/MSG-Community-Edition#3]
When launching with Prism Launcher, the game crashes before it can load up. The message that comes with this is the following; "The java binary "" couldn't be found. Please fix the java path override in the instance's settings or disable it."

**Comment by PewPewCricket** [comment]
This is an issue with your java install, please download java 8 and change your java installation in your instance settings, for more help ask the folks at PrismLauncher on how to do this, this is not an issue with the mod pack.
